Version: 9

Clean-Console: false

DATABASE:
  # true = MySQL, false = SQLite
  ENABLED: false
  ADDRESS: '127.0.0.1'
  PORT: 3306
  DATABASE: 'lifesteal'
  USERNAME: 'username'
  PASSWORD: 'password'

# State how many hearts players should transfer on player death.
HeartsToTransfer: 1
DefaultHearts: 10
# put -1 for no limit.
Max-Hearts: -1
DisableTotem: true
DisableMilkCure: true

# put -1 for no cooldown.
# Values should be in seconds.
Cooldowns:
  Heart-Consume: -1
  Heart-Craft: -1
  Heart-Withdraw: -1

# Put [] to disable any of these.
Disabled-Worlds:
  Heart-Craft:
    - 'world_nether'
    - 'world_the_end'
  Heart-Withdraw:
    - 'world_nether'
    - 'world_the_end'
  Heart-Drops:
    Player-Kill:
      - 'world_nether'
      - 'world_the_end'
    Other:
      - 'world_nether'
      - 'world_the_end'
  Heart-Consume:
    - 'world_nether'
    - 'world_the_end'
Heart:
  Properties:
    ItemType: 'PAPER'
    Name: '<gradient:#f6c0ba:#f89999> <b><color:#e01e37>❥</color> Heart'
    Lore:
      - '<gradient:#e01e37:#f72585>══════════════════════════════════════'
      - '<gradient:#f89999:#f6c0ba><b>This is a placeholder heart.'
      - ''
      - '<gradient:#f89999:#f6c0ba>This will be turned into a normal,'
      - '<gradient:#f89999:#f6c0ba>blessed or cursed heart after crafting.'
      - '<gradient:#f72585:#e01e37>══════════════════════════════════════'
    ModelData: 123456
  #Heart item recipe, it is a shaped recipe.
  Recipe:
    A: 'DIAMOND'
    B: 'GOLD_INGOT'
    C: 'DIAMOND'
    D: 'GOLD_INGOT'
    E: 'NETHER_STAR'
    F: 'GOLD_INGOT'
    G: 'DIAMOND'
    H: 'GOLD_INGOT'
    I: 'DIAMOND'
#Crafting table representation.
#  ╔═══╦═══╦═══╗
#  ║ A ║ B ║ C ║
#  ╠═══╬═══╬═══╣
#  ║ D ║ E ║ F ║
#  ╠═══╬═══╬═══╣
#  ║ G ║ H ║ I ║
#  ╚═══╩═══╩═══╝

# What happens after player looses all hearts.
#Valid values are,
#DEAD = Spectates own body npc,
#SPIRIT = Roams around freely in spectator mode,
#BANNED = Gets banned, only works if death bans are enabled.
Elimination: 'SPIRIT'

# What happens to player's inventory when they get eliminated.
# Valid values are,
# DROP = Drops player inventory where they were eliminated,
# SAVE_TO_RESTORE = Saves the inventory and restores it when player is revived,
# CLEAR = Clears the inventory, don't use this please, :(
# NONE = Nothing happens, use this if you're going to use ban mode on elimination.
InventoryMode: 'SAVE_TO_RESTORE'
# Same as Inventory mode.
ExperienceMode: 'SAVE_TO_RESTORE'

Ban-Command-URI: 'ban <player> 3d [LifeSteal] - Eliminated. -s'
UnBan-Command-URI: 'unban <player> 3d [LifeSteal] - Revived. -s'

Spirits:
  Black-Hearts: true
  Spirit-Model:
    Enabled: true
    ItemType: 'GOLDEN_HELMET'
    Name: '<#f89999>Spirit Cloak'
    Lore: [ " " ]
    ModelData: 123456
  #   leave these settings as is to get a perfect spirit concept.
  Hearts: 1
  GameMode: 'ADVENTURE'
  Invisible: true
  Invulnerable: true
  CanPickupItems: false
  Collidable: false
  SleepingIgnored: true
  Silent: true